### ISSUE TITLE
got coredump when group not exist

### ISSUE THREAD

**Issue by millken** [vozlt/nginx-module-vts#56]
http://127.0.0.1:83/status/control?cmd=status&group=test

```
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005851cf in ngx_http_vhost_traffic_status_node_control_range_set
    (control=0x7f40c32e61a8)
    at ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:2644
2644            if (control->zone->len == 0) {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.4.x86_64 libgcc-4.8.5-4.el7.x86_64 lua-5.1.4-14.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 pcre-8.32-15.el7.x86_64 sssd-client-1.13.0-40.el7_2.2.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00000000005851cf in ngx_http_vhost_traffic_status_node_control_range_set
    (control=0x7f40c32e61a8)
    at ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:2644
#1  0x0000000000582439 in ngx_http_vhost_traffic_status_display_handler_control
    (r=0x7f40c32e51a0)
    at ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:1516
#2  0x0000000000581f39 in ngx_http_vhost_traffic_status_display_handler (
    r=0x7f40c32e51a0)
    at ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:1386
#3  0x00000000004a06e1 in ngx_http_core_content_phase (r=0x7f40c32e51a0, 
    ph=0x7f40c33041c8) at src/http/ngx_http_core_module.c:1368
#4  0x000000000049f227 in ngx_http_core_run_phases (r=0x7f40c32e51a0)
    at src/http/ngx_http_core_module.c:845
#5  0x000000000049f195 in ngx_http_handler (r=0x7f40c32e51a0)
    at src/http/ngx_http_core_module.c:828
#6  0x00000000004aedfa in ngx_http_process_request (r=0x7f40c32e51a0)
    at src/http/ngx_http_request.c:1914
#7  0x00000000004ad75e in ngx_http_process_request_headers (rev=0x7f40c31b8310)
    at src/http/ngx_http_request.c:1346
#8  0x00000000004acb41 in ngx_http_process_request_line (rev=0x7f40c31b8310)
    at src/http/ngx_http_request.c:1026
#9  0x00000000004ab7af in ngx_http_wait_request_handler (rev=0x7f40c31b8310)
    at src/http/ngx_http_request.c:503
#10 0x000000000048db99 in ngx_epoll_process_events (cycle=0x7f40c32b5000, 
    timer=924, flags=1) at src/event/modules/ngx_epoll_module.c:907
#11 0x000000000047cc89 in ngx_process_events_and_timers (cycle=0x7f40c32b5000)
    at src/event/ngx_event.c:242
#12 0x000000000048b40b in ngx_worker_process_cycle (cycle=0x7f40c32b5000, 
    data=0x1) at src/os/unix/ngx_process_cycle.c:753
#13 0x0000000000487d07 in ngx_spawn_process (cycle=0x7f40c32b5000, 
    proc=0x48b316 <ngx_worker_process_cycle>, data=0x1, 
    name=0x71a783 "worker process", respawn=-3)
    at src/os/unix/ngx_process.c:198
#14 0x000000000048a247 in ngx_start_worker_processes (cycle=0x7f40c32b5000, 
    n=2, type=-3) at src/os/unix/ngx_process_cycle.c:358
#15 0x0000000000489864 in ngx_master_process_cycle (cycle=0x7f40c32b5000)
    at src/os/unix/ngx_process_cycle.c:130
#16 0x000000000044be59 in main (argc=3, argv=0x7ffdf3a760d8)
    at src/core/nginx.c:367

```

**Comment by vozlt** [comment]
Hi, Thanks for reporting.
The nginx-module-vts has been updated as suggested.(https://github.com/vozlt/nginx-module-vts/commit/64e00555a788b93fd279f4c09db69795cf6414db).
Please test.
