### ISSUE TITLE
nginx built with nginx-module-vts often crashes

### ISSUE THREAD

**Issue by drook** [vozlt/nginx-module-vts#59]
nginx built with nginx-module-vts often crashes. and it's a shame because it's a beautiful module.

Env:

nginx-1.11.5
Solaris 11.2 amd64
GCC:

````gcc
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/lto-wrapper
Target: i386-pc-solaris2.11
Configured with: /builds/hudson/workspace/nightly-update/build/i386/components/gcc45/gcc-4.5.2/configure CC=/ws/on11update-tools/SUNWspro/sunstudio12.1/bin/cc CXX=/ws/on11update-tools/SUNWspro/sunstudio12.1/bin/CC --prefix=/usr/gcc/4.5 --mandir=/usr/gcc/4.5/share/man --bindir=/usr/gcc/4.5/bin --libdir=/usr/gcc/4.5/lib --sbindir=/usr/gcc/4.5/sbin --infodir=/usr/gcc/4.5/share/info --libexecdir=/usr/gcc/4.5/lib --enable-languages=c,c++,fortran,objc --enable-shared --with-gmp-include=/usr/include/gmp --with-mpfr-include=/usr/include/mpfr --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/usr/gnu/bin/as CFLAGS='-g -O2 '
Thread model: posix
gcc version 4.5.2 (GCC)
````

Backtrace (brief and full, got handful of these):

````bt
_nginx_505_%c_6289 -hyperion]# gdb /usr/local/nginx/sbin/nginx.old core_hyperion 
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i386-pc-solaris2.11".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/nginx/sbin/nginx.old...done.

warning: core file may not match specified executable file.
[New LWP 1]
[New LWP 1]
[Thread debugging using libthread_db enabled]
[New Thread 1 (LWP 1)]
Core was generated by `/usr/local/nginx/sbin/nginx'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000006a9a3c in ngx_http_vhost_traffic_status_shm_add_upstream (
    r=0xaa0250)
    at /home/emz/src/nginx-module-vts-0.1.10/src/ngx_http_vhost_traffic_status_module.c:2329
2329        dst.len = (uscf->port ? 0 : uscf->host.len + sizeof("@") - 1) + state[0].peer->len;
(gdb) bt
#0  0x00000000006a9a3c in ngx_http_vhost_traffic_status_shm_add_upstream (
    r=0xaa0250)
    at /home/emz/src/nginx-module-vts-0.1.10/src/ngx_http_vhost_traffic_status_module.c:2329
#1  0x00000000006a7359 in ngx_http_vhost_traffic_status_handler (r=0xaa0250)
    at /home/emz/src/nginx-module-vts-0.1.10/src/ngx_http_vhost_traffic_status_module.c:1178
#2  0x0000000000614126 in ngx_http_log_request (r=0xaa0250)
    at src/http/ngx_http_request.c:3519
#3  0x0000000000613f92 in ngx_http_free_request (r=0xaa0250, rc=0)
    at src/http/ngx_http_request.c:3466
#4  0x0000000000613e3d in ngx_http_close_request (r=0xaa0250, rc=0)
    at src/http/ngx_http_request.c:3413
#5  0x0000000000613aa1 in ngx_http_lingering_close_handler (rev=0x1186120)
    at src/http/ngx_http_request.c:3273
#6  0x00000000005f189d in ngx_devpoll_process_events (cycle=0xb79cd0, 
    timer=791, flags=1) at src/event/modules/ngx_devpoll_module.c:510
#7  0x00000000005e1d7a in ngx_process_events_and_timers (cycle=0xb79cd0)
    at src/event/ngx_event.c:242
#8  0x00000000005ee0e6 in ngx_worker_process_cycle (cycle=0xb79cd0, data=0x3)
    at src/os/unix/ngx_process_cycle.c:753
#9  0x00000000005eb027 in ngx_spawn_process (cycle=0xb79cd0, 
    proc=0x5ee027 <ngx_worker_process_cycle>, data=0x3, 
---Type <return> to continue, or q <return> to quit--- 
    name=0x90a3d8 "worker process", respawn=-4)
    at src/os/unix/ngx_process.c:198
#10 0x00000000005ed2ba in ngx_start_worker_processes (cycle=0xb79cd0, n=4, 
    type=-4) at src/os/unix/ngx_process_cycle.c:358
#11 0x00000000005ece35 in ngx_master_process_cycle (cycle=0xb79cd0)
    at src/os/unix/ngx_process_cycle.c:243
#12 0x00000000005b0fa7 in main (argc=1, argv=0xffff80ffbffffcf8)
    at src/core/nginx.c:367
(gdb) bt full
#0  0x00000000006a9a3c in ngx_http_vhost_traffic_status_shm_add_upstream (
    r=0xaa0250)
    at /home/emz/src/nginx-module-vts-0.1.10/src/ngx_http_vhost_traffic_status_module.c:2329
        p = 0xaa0250 "HTTP"
        type = 0
        rc = -139639050475968
        host = 0x119dd20
        key = {len = 18446604434659075584, 
          data = 0x6a9751 <ngx_http_vhost_traffic_status_shm_add_server+266> "H\203\304X[�\303UH\211\345H\203\354\060H\211}\330H\213E\330H\213@\030H\213\025\rm5"}
        dst = {len = 18472251, data = 0xffff80ffbfffe5c0 "\033"}
        i = 25926512
        u = 0x119cbe0
        state = 0x119d790
        uscf = 0x166bce0
        uscfp = 0x18da262
        umcf = 0x1b
#1  0x00000000006a7359 in ngx_http_vhost_traffic_status_handler (r=0xaa0250)
    at /home/emz/src/nginx-module-vts-0.1.10/src/ngx_http_vhost_traffic_status_module.c:1178
        rc = 0
---Type <return> to continue, or q <return> to quit--- 
        ctx = 0xb7dbb0
        vtscf = 0x18bd6f0
#2  0x0000000000614126 in ngx_http_log_request (r=0xaa0250)
    at src/http/ngx_http_request.c:3519
        i = 1
        n = 2
        log_handler = 0x1adc8f0
        cmcf = 0xb7bb30
#3  0x0000000000613f92 in ngx_http_free_request (r=0xaa0250, rc=0)
    at src/http/ngx_http_request.c:3466
        log = 0x19af4e0
        pool = 0x5e8f3f <ngx_unix_recv+63>
        linger = {l_onoff = -1073748224, l_linger = -32513}
        cln = 0x0
        ctx = 0x0
        clcf = 0x1000
#4  0x0000000000613e3d in ngx_http_close_request (r=0xaa0250, rc=0)
    at src/http/ngx_http_request.c:3413
        c = 0x12a3de0
#5  0x0000000000613aa1 in ngx_http_lingering_close_handler (rev=0x1186120)
    at src/http/ngx_http_request.c:3273
        n = 0
        timer = 30
---Type <return> to continue, or q <return> to quit---
        c = 0x12a3de0
        r = 0xaa0250
        clcf = 0x400
        buffer = "\000\000\000\000\000\000\000\000^\335\220\000\000\000\000\000\224\a\000\000\000\000\000\000\034\351\377�\377\200\377\377\340\364\232\001\000\000\000\000z}8�\377\200\377\377", '\000' <repeats 25 times>, "\332\031\001\000\000\000\000\240\347\377�\377\200\377\377@\233^", '\000' <repeats 21 times>, "\003\000\000\000\000\000\000\000\222\001\000\000\000\000\000\000p\351\377�\377\200\377\377\200\227^\000\000\000\000\000 \350\377�\377\200\377\377'Fa\000\000\000\000\000\320\317\031\001\000\000\000\000\377\350\377�\377\200\377\377\325\006\000\000\000\000\000\000/\352\377�\377\200\377\377P\002\252\000\000\000\000\000"...
#6  0x00000000005f189d in ngx_devpoll_process_events (cycle=0xb79cd0, 
    timer=791, flags=1) at src/event/modules/ngx_devpoll_module.c:510
        events = 1
        revents = 1
        rc = -32513
        n = 18446604434659080272
        fd = 44
        err = 0
        i = 0
        level = 6176106
        instance = 0
        rev = 0x1186120
---Type <return> to continue, or q <return> to quit---
        wev = 0x10acba0
        queue = 0xfa0
        c = 0x12a3de0
        pfd = {fd = -1073743872, events = -32513, revents = -1}
        dvp = {dp_fds = 0x11672f0, dp_nfds = 1024, dp_timeout = 791}
#7  0x00000000005e1d7a in ngx_process_events_and_timers (cycle=0xb79cd0)
    at src/event/ngx_event.c:242
        flags = 1
        timer = 791
        delta = 1478589441259
#8  0x00000000005ee0e6 in ngx_worker_process_cycle (cycle=0xb79cd0, data=0x3)
    at src/os/unix/ngx_process_cycle.c:753
        worker = 3
#9  0x00000000005eb027 in ngx_spawn_process (cycle=0xb79cd0, 
    proc=0x5ee027 <ngx_worker_process_cycle>, data=0x3, 
    name=0x90a3d8 "worker process", respawn=-4)
    at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 8
#10 0x00000000005ed2ba in ngx_start_worker_processes (cycle=0xb79cd0, n=4, 
    type=-4) at src/os/unix/ngx_process_cycle.c:358
        i = 3
---Type <return> to continue, or q <return> to quit---
        ch = {command = 1, pid = 6288, slot = 7, fd = 10}
#11 0x00000000005ece35 in ngx_master_process_cycle (cycle=0xb79cd0)
    at src/os/unix/ngx_process_cycle.c:243
        title = 0x15ccd3c "master process /usr/local/nginx/sbin/nginx"
        p = 0x15ccd66 ""
        size = 43
        i = 1
        n = 18446604434659080784
        sigio = 0
        set = {__sigbits = {0, 0, 0, 0}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {
            tv_sec = 206158430232, tv_usec = -139639050470880}}
        live = 1
        delay = 0
        ls = 0x0
        ccf = 0xb7b190
#12 0x00000000005b0fa7 in main (argc=1, argv=0xffff80ffbffffcf8)
    at src/core/nginx.c:367
        b = 0x905f93 <_init+19>
        log = 0xa13f20 <ngx_log>
        i = 18446604434659081464
        cycle = 0xa869d0
        init_cycle = {conf_ctx = 0x0, pool = 0xa68880, 
---Type <return> to continue, or q <return> to quit---
          log = 0xa13f20 <ngx_log>, new_log = {log_level = 0, file = 0x0, 
            connection = 0, disk_full_time = 0, handler = 0x0, data = 0x0, 
            writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, 
          log_use_stderr = 0, files = 0x0, free_connections = 0x0, 
          free_connection_n = 0, modules = 0x0, modules_n = 0, 
          modules_used = 0, reusable_connections_queue = {prev = 0x0, 
            next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0, 
            nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, 
            nalloc = 0, pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, 
            size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, 
            part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, 
            pool = 0x0}, shared_memory = {last = 0x0, part = {elts = 0x0, 
              nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, 
          write_events = 0x0, old_cycle = 0x0, conf_file = {len = 32, 
            data = 0xa688d0 "\350\210\246"}, conf_param = {len = 0, 
            data = 0x0}, conf_prefix = {len = 22, 
            data = 0xa688d0 "\350\210\246"}, prefix = {len = 17, 
            data = 0x906d86 "/usr/local/nginx/"}, lock_file = {len = 0, 
            data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = 0xffff80ffbffffce0
        ccf = 0xa88520
(gdb) 
(gdb)
````

**Comment by vozlt** [comment]
Hi, I'm not entirely sure, but I have fixed the suspected line in code a few months ago.
I tagged it at [v0.1.11](https://github.com/vozlt/nginx-module-vts/tree/v0.1.11) just now.
Please test...
Latest commit: https://github.com/vozlt/nginx-module-vts/commit/b7918bb3e50e16293a975d9f2af8d1c606132597
