### ISSUE TITLE
Segfault with 0.1.14

### ISSUE THREAD

**Issue by kgs** [vozlt/nginx-module-vts#76]
Hi,

I am using nginx 0.11.2, with lua-nginx 0.10.7 and ngx-devel-kit 0.3.0. VTS in 0.1.14 version.

In my setup, when I have more than 10 servers in one upstream and I want to see status page - Nginx workers crashes.

VTS configuration is standard:

```
  vhost_traffic_status_zone;
  ..
  location /status-vts {
       vhost_traffic_status_display;
       vhost_traffic_status_display_format html;
    }
```

gdb bt from core is as follows:

```
#0  0x00007f9e3e6fc672 in __memset_sse2 () from /lib64/libc.so.6
#1  0x000000000041d06c in ngx_pcalloc (pool=0x7f9e4006f2c0, size=23) at src/core/ngx_palloc.c:304
#2  0x0000000000515a5a in ngx_http_vhost_traffic_status_node_generate_key (pool=0x7f9e4006f2c0, buf=0x7ffd39a0cee0, dst=0x7ffd39a0ced0, type=2)
    at /srv/teamcity/work/10f1a14303cc46b1/modules/nginx-module-vts-0.1.14/src/ngx_http_vhost_traffic_status_node.c:21
#3  0x000000000051d6e2 in ngx_http_vhost_traffic_status_display_set_upstream_group (r=0x7f9e4006f310, buf=0x7f9e40071ed5 ",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0")
    at /srv/teamcity/work/10f1a14303cc46b1/modules/nginx-module-vts-0.1.14/src/ngx_http_vhost_traffic_status_display.c:1094
#4  0x000000000051dfe3 in ngx_http_vhost_traffic_status_display_set (r=0x7f9e4006f310,
    buf=0x7f9e40070bcc "\"servers\":[{\"server\":\"10.1.2.11:80\",\"requestCounter\":0,\"inBytes\":0,\"outBytes\":0,\"responses\":{\"1xx\":0,\"2xx\":0,\"3xx\":0,\"4xx\":0,\"5xx\":0},\"requestMsec\":0,\"requestMsecs\":{\"times\":[],\"msecs\":[]},\"responseMs"...) at /srv/teamcity/work/10f1a14303cc46b1/modules/nginx-module-vts-0.1.14/src/ngx_http_vhost_traffic_status_display.c:1302
#5  0x000000000051b3f0 in ngx_http_vhost_traffic_status_display_handler_default (r=0x7f9e4006f310) at /srv/teamcity/work/10f1a14303cc46b1/modules/nginx-module-vts-0.1.14/src/ngx_http_vhost_traffic_status_display.c:395
#6  0x000000000051a76c in ngx_http_vhost_traffic_status_display_handler (r=0x7f9e4006f310) at /srv/teamcity/work/10f1a14303cc46b1/modules/nginx-module-vts-0.1.14/src/ngx_http_vhost_traffic_status_display.c:56
#7  0x0000000000464068 in ngx_http_core_content_phase (r=0x7f9e4006f310, ph=0x7f9e3fff75e0) at src/http/ngx_http_core_module.c:1368
#8  0x0000000000462f7f in ngx_http_core_run_phases (r=0x7f9e4006f310) at src/http/ngx_http_core_module.c:845
#9  0x0000000000462eed in ngx_http_handler (r=0x7f9e4006f310) at src/http/ngx_http_core_module.c:828
#10 0x0000000000471951 in ngx_http_process_request (r=0x7f9e4006f310) at src/http/ngx_http_request.c:1914
#11 0x0000000000470427 in ngx_http_process_request_headers (rev=0x7f9e3bfe27d0) at src/http/ngx_http_request.c:1346
#12 0x000000000046f9d1 in ngx_http_process_request_line (rev=0x7f9e3bfe27d0) at src/http/ngx_http_request.c:1026
#13 0x000000000046e8b9 in ngx_http_wait_request_handler (rev=0x7f9e3bfe27d0) at src/http/ngx_http_request.c:503
#14 0x0000000000454b0b in ngx_epoll_process_events (cycle=0x7f9e3ffa7c80, timer=6, flags=1) at src/event/modules/ngx_epoll_module.c:900
#15 0x0000000000447157 in ngx_process_events_and_timers (cycle=0x7f9e3ffa7c80) at src/event/ngx_event.c:242
#16 0x000000000045290a in ngx_worker_process_cycle (cycle=0x7f9e3ffa7c80, data=0x0) at src/os/unix/ngx_process_cycle.c:753
#17 0x000000000044f9ca in ngx_spawn_process (cycle=0x7f9e3ffa7c80, proc=0x45284e <ngx_worker_process_cycle>, data=0x0, name=0x523bb0 "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
#18 0x0000000000451b2d in ngx_start_worker_processes (cycle=0x7f9e3ffa7c80, n=16, type=-3) at src/os/unix/ngx_process_cycle.c:358
#19 0x000000000045128d in ngx_master_process_cycle (cycle=0x7f9e3ffa7c80) at src/os/unix/ngx_process_cycle.c:130
#20 0x0000000000419259 in main (argc=3, argv=0x7ffd39a0d928) at src/core/nginx.c:367
```

When servers number in upstream is small, then no problem occurs.

Any ideas?

**Comment by vozlt** [comment]
Thanks for reporting this error.
I fixed suspected sections just now and re-tagged to v0.1.14.
If the above error occurs in [latest commit](https://github.com/vozlt/nginx-module-vts/commit/9c0f90bae5619aa85bfac96fa9739f8117fb5bc6), then please test in the nginx-module-vts v0.1.12 version and let me know if occurs.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/9c0f90bae5619aa85bfac96fa9739f8117fb5bc6

**Comment by kgs** [comment]
Short test shows that it's working now. Thanks!
